// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: posts.proto

package posts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PostId         string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Latitude       float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_posts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Post) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Post) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Post) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Post) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Post) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreatePostRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Latitude       float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_posts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreatePostRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreatePostRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreatePostRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CreatePostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostResponse) Reset() {
	*x = CreatePostResponse{}
	mi := &file_posts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostResponse) ProtoMessage() {}

func (x *CreatePostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostResponse.ProtoReflect.Descriptor instead.
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPostsRequest) Reset() {
	*x = GetUserPostsRequest{}
	mi := &file_posts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPostsRequest) ProtoMessage() {}

func (x *GetUserPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPostsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPostsRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPostsRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetUserPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPostsResponse) Reset() {
	*x = GetUserPostsResponse{}
	mi := &file_posts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPostsResponse) ProtoMessage() {}

func (x *GetUserPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPostsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPostsResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserPostsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPostsByLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Radius        float64                `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsByLocationRequest) Reset() {
	*x = GetPostsByLocationRequest{}
	mi := &file_posts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsByLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByLocationRequest) ProtoMessage() {}

func (x *GetPostsByLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByLocationRequest.ProtoReflect.Descriptor instead.
func (*GetPostsByLocationRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{5}
}

func (x *GetPostsByLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetPostsByLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetPostsByLocationRequest) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *GetPostsByLocationRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetPostsByLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsByLocationResponse) Reset() {
	*x = GetPostsByLocationResponse{}
	mi := &file_posts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsByLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByLocationResponse) ProtoMessage() {}

func (x *GetPostsByLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByLocationResponse.ProtoReflect.Descriptor instead.
func (*GetPostsByLocationResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{6}
}

func (x *GetPostsByLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIdRequest) Reset() {
	*x = GetPostByIdRequest{}
	mi := &file_posts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIdRequest) ProtoMessage() {}

func (x *GetPostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPostByIdRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{7}
}

func (x *GetPostByIdRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetPostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIdResponse) Reset() {
	*x = GetPostByIdResponse{}
	mi := &file_posts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIdResponse) ProtoMessage() {}

func (x *GetPostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPostByIdResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{8}
}

func (x *GetPostByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdatePostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostByIdRequest) Reset() {
	*x = UpdatePostByIdRequest{}
	mi := &file_posts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostByIdRequest) ProtoMessage() {}

func (x *UpdatePostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostByIdRequest.ProtoReflect.Descriptor instead.
func (*UpdatePostByIdRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePostByIdRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *UpdatePostByIdRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePostByIdRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdatePostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePostByIdResponse) Reset() {
	*x = UpdatePostByIdResponse{}
	mi := &file_posts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePostByIdResponse) ProtoMessage() {}

func (x *UpdatePostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePostByIdResponse.ProtoReflect.Descriptor instead.
func (*UpdatePostByIdResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePostByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePostByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostByIdRequest) Reset() {
	*x = DeletePostByIdRequest{}
	mi := &file_posts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostByIdRequest) ProtoMessage() {}

func (x *DeletePostByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostByIdRequest.ProtoReflect.Descriptor instead.
func (*DeletePostByIdRequest) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{11}
}

func (x *DeletePostByIdRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type DeletePostByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostByIdResponse) Reset() {
	*x = DeletePostByIdResponse{}
	mi := &file_posts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostByIdResponse) ProtoMessage() {}

func (x *DeletePostByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_posts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostByIdResponse.ProtoReflect.Descriptor instead.
func (*DeletePostByIdResponse) Descriptor() ([]byte, []int) {
	return file_posts_proto_rawDescGZIP(), []int{12}
}

func (x *DeletePostByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_posts_proto protoreflect.FileDescriptor

const file_posts_proto_rawDesc = "" +
	"\n" +
	"\vposts.proto\x12\x05posts\"\x89\x02\n" +
	"\x04Post\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\xa6\x01\n" +
	"\x11CreatePostRequest\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\".\n" +
	"\x12CreatePostResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x13GetUserPostsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"0\n" +
	"\x14GetUserPostsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x83\x01\n" +
	"\x19GetPostsByLocationRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x01R\x06radius\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"6\n" +
	"\x1aGetPostsByLocationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x12GetPostByIdRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"/\n" +
	"\x13GetPostByIdResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"`\n" +
	"\x15UpdatePostByIdRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"2\n" +
	"\x16UpdatePostByIdResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x15DeletePostByIdRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"2\n" +
	"\x16DeletePostByIdResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd9\x03\n" +
	"\fPostsService\x12A\n" +
	"\n" +
	"CreatePost\x12\x18.posts.CreatePostRequest\x1a\x19.posts.CreatePostResponse\x12D\n" +
	"\vGetPostById\x12\x19.posts.GetPostByIdRequest\x1a\x1a.posts.GetPostByIdResponse\x12G\n" +
	"\fGetUserPosts\x12\x1a.posts.GetUserPostsRequest\x1a\x1b.posts.GetUserPostsResponse\x12Y\n" +
	"\x12GetPostsByLocation\x12 .posts.GetPostsByLocationRequest\x1a!.posts.GetPostsByLocationResponse\x12M\n" +
	"\x0eUpdatePostById\x12\x1c.posts.UpdatePostByIdRequest\x1a\x1d.posts.UpdatePostByIdResponse\x12M\n" +
	"\x0eDeletePostById\x12\x1c.posts.DeletePostByIdRequest\x1a\x1d.posts.DeletePostByIdResponseB\x0fZ\rpkg/api/postsb\x06proto3"

var (
	file_posts_proto_rawDescOnce sync.Once
	file_posts_proto_rawDescData []byte
)

func file_posts_proto_rawDescGZIP() []byte {
	file_posts_proto_rawDescOnce.Do(func() {
		file_posts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_posts_proto_rawDesc), len(file_posts_proto_rawDesc)))
	})
	return file_posts_proto_rawDescData
}

var file_posts_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_posts_proto_goTypes = []any{
	(*Post)(nil),                       // 0: posts.Post
	(*CreatePostRequest)(nil),          // 1: posts.CreatePostRequest
	(*CreatePostResponse)(nil),         // 2: posts.CreatePostResponse
	(*GetUserPostsRequest)(nil),        // 3: posts.GetUserPostsRequest
	(*GetUserPostsResponse)(nil),       // 4: posts.GetUserPostsResponse
	(*GetPostsByLocationRequest)(nil),  // 5: posts.GetPostsByLocationRequest
	(*GetPostsByLocationResponse)(nil), // 6: posts.GetPostsByLocationResponse
	(*GetPostByIdRequest)(nil),         // 7: posts.GetPostByIdRequest
	(*GetPostByIdResponse)(nil),        // 8: posts.GetPostByIdResponse
	(*UpdatePostByIdRequest)(nil),      // 9: posts.UpdatePostByIdRequest
	(*UpdatePostByIdResponse)(nil),     // 10: posts.UpdatePostByIdResponse
	(*DeletePostByIdRequest)(nil),      // 11: posts.DeletePostByIdRequest
	(*DeletePostByIdResponse)(nil),     // 12: posts.DeletePostByIdResponse
}
var file_posts_proto_depIdxs = []int32{
	1,  // 0: posts.PostsService.CreatePost:input_type -> posts.CreatePostRequest
	7,  // 1: posts.PostsService.GetPostById:input_type -> posts.GetPostByIdRequest
	3,  // 2: posts.PostsService.GetUserPosts:input_type -> posts.GetUserPostsRequest
	5,  // 3: posts.PostsService.GetPostsByLocation:input_type -> posts.GetPostsByLocationRequest
	9,  // 4: posts.PostsService.UpdatePostById:input_type -> posts.UpdatePostByIdRequest
	11, // 5: posts.PostsService.DeletePostById:input_type -> posts.DeletePostByIdRequest
	2,  // 6: posts.PostsService.CreatePost:output_type -> posts.CreatePostResponse
	8,  // 7: posts.PostsService.GetPostById:output_type -> posts.GetPostByIdResponse
	4,  // 8: posts.PostsService.GetUserPosts:output_type -> posts.GetUserPostsResponse
	6,  // 9: posts.PostsService.GetPostsByLocation:output_type -> posts.GetPostsByLocationResponse
	10, // 10: posts.PostsService.UpdatePostById:output_type -> posts.UpdatePostByIdResponse
	12, // 11: posts.PostsService.DeletePostById:output_type -> posts.DeletePostByIdResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_posts_proto_init() }
func file_posts_proto_init() {
	if File_posts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_posts_proto_rawDesc), len(file_posts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_posts_proto_goTypes,
		DependencyIndexes: file_posts_proto_depIdxs,
		MessageInfos:      file_posts_proto_msgTypes,
	}.Build()
	File_posts_proto = out.File
	file_posts_proto_goTypes = nil
	file_posts_proto_depIdxs = nil
}
